# Generated by Django 4.2 on 2023-04-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
            options={"db_table": "customer",},
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("word", models.CharField(db_column="word", max_length=32)),
                ("translate", models.CharField(db_column="translate", max_length=256)),
                ("add_date", models.DateTimeField(db_column="add_dttm")),
                (
                    "customer_added",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="LinguaLearn.customuser",
                    ),
                ),
            ],
            options={"db_table": "dictionary",},
        ),
    ]
