# Generated by Django 4.2 on 2023-04-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Content", new_name="Dictionary",),
    ]
