# Generated by Django 4.2 on 2023-04-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0002_rename_content_dictionary"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(name="customuser", table="lingualearn_customer",),
        migrations.AlterModelTable(name="dictionary", table="lingualearn_dictionary",),
        migrations.CreateModel(
            name="CustomerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("start_dttm", models.DateTimeField()),
                ("end_dttm", models.DateTimeField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="LinguaLearn.customuser",
                    ),
                ),
            ],
            options={"db_table": "lingualearn_customer_session",},
        ),
    ]
