# Generated by Django 4.2 on 2023-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0003_customuser_avatar_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="card_img",
            field=models.FileField(blank=True, null=True, upload_to="cards/"),
        ),
    ]
