# Generated by Django 4.2 on 2023-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0004_dictionary_card_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="speech",
            field=models.FileField(blank=True, null=True, upload_to="speech/"),
        ),
    ]
