# Generated by Django 4.2 on 2023-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0005_dictionary_speech"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(null=True),
        ),
    ]
