# Generated by Django 4.2 on 2023-04-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0006_customuser_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_date",
            field=models.DateTimeField(null=True),
        ),
    ]
