# Generated by Django 4.2 on 2023-04-27 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0007_customuser_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 28, 0, 36, 3, 41182), null=True
            ),
        ),
    ]
