# Generated by Django 4.2 on 2023-05-01 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0022_alter_customersession_end_dttm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 1, 8, 0, 47, 200452), null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="add_date",
            field=models.DateTimeField(
                db_column="add_dttm",
                default=datetime.datetime(2023, 5, 1, 8, 0, 47, 200594),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word",
            field=models.CharField(db_column="word", max_length=32, unique=True),
        ),
    ]
