# Generated by Django 4.2 on 2023-05-01 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0024_alter_customuser_registration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 1, 8, 1, 48, 256179), null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="add_date",
            field=models.DateTimeField(
                db_column="add_dttm",
                default=datetime.datetime(2023, 5, 1, 8, 1, 48, 256321),
                null=True,
            ),
        ),
    ]
