# Generated by Django 4.2 on 2023-05-01 06:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0025_alter_customuser_registration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictionary",
            name="customer_id",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.PROTECT,
                to="LinguaLearn.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 1, 9, 27, 23, 762204), null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="add_date",
            field=models.DateTimeField(
                db_column="add_dttm",
                default=datetime.datetime(2023, 5, 1, 9, 27, 23, 762341),
                null=True,
            ),
        ),
    ]
