# Generated by Django 4.2 on 2023-05-01 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0026_dictionary_customer_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="dictionary", name="customer_id",),
        migrations.AlterField(
            model_name="customuser",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 1, 9, 31, 27, 540188), null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="add_date",
            field=models.DateTimeField(
                db_column="add_dttm",
                default=datetime.datetime(2023, 5, 1, 9, 31, 27, 540339),
                null=True,
            ),
        ),
    ]
