# Generated by Django 4.2 on 2023-05-01 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0031_alter_customuser_registration_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customersession", old_name="customer_id", new_name="customer",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 1, 16, 32, 0, 799132), null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="add_date",
            field=models.DateTimeField(
                db_column="add_dttm",
                default=datetime.datetime(2023, 5, 1, 16, 32, 0, 799485),
                null=True,
            ),
        ),
    ]
