# Generated by Django 4.2 on 2023-05-01 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LinguaLearn", "0032_rename_customer_id_customersession_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 1, 16, 32, 42, 820303), null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="add_date",
            field=models.DateTimeField(
                db_column="add_dttm",
                default=datetime.datetime(2023, 5, 1, 16, 32, 42, 820641),
                null=True,
            ),
        ),
    ]
